OBJS = uvm_dpi.o
INC = $(DSIM_HOME)/include
CC = gcc
CCFLAGS = -DDSIM -I$(DSIM_HOME)/include

libuvm_dpi.so: $(OBJS)
	$(CC) -shared -fPIC -o libuvm_dpi.so $(OBJS)

%.o: %.cc
	$(CC) $(CCFLAGS) -O2 -c -fPIC $*.cc -o $*.o

clean:
	@-rm -f *.o libuvm_dpi.so
